app/home/forms.py
from flask_wtf import Form
from wtforms import TextField, IntegerField, TextAreaField, SubmitField, RadioField,SelectField

from wtforms import validators, ValidationError

class ContactForm(Form):
   name = TextField("Name Of Student",[validators.Required("Please enter your name.")])
   Gender = RadioField('Gender', choices = [('M','Male'),('F','Female')])
   Address = TextAreaField("Address")
   
   email = TextField("Email",[validators.Required("Please enter your email address."),
      validators.Email("Please enter your email address.")])
   
   Age = IntegerField("age")
   language = SelectField('Languages', choices = [('cpp', 'C++'), 
      ('py', 'Python')])
   submit = SubmitField("Send")

app/__init__.py
from flask import Flask
from flask_pymongo import PyMongo
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
import os

app = Flask(__name__)

app.config.from_pyfile('config.py')
app.secret_key = os.urandom(24)

mongo = PyMongo(app)
bcrypt = Bcrypt(app)
login_manager = LoginManager(app)

from app.home import home as home_blueprint
app.register_blueprint(home_blueprint)

from app.user import user as user_blueprint
app.register_blueprint(user_blueprint, url_prefix='/user')

from app.master import master as master_blueprint
app.register_blueprint(master_blueprint, url_prefix='/master')

login_manager.login_view = "home.login"

app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from app.home import routes

app/home/routes.py
from flask import render_template, request, redirect, url_for, session, flash
from wtforms import ValidationError,StringField, PasswordField, validators
from flask_login import login_user
from app.home import home
from app import mongo, bcrypt, login_manager
from app.home.user_loging_manager import User
from flask import request, redirect
from werkzeug.utils import secure_filename
import os,shutil
import hashlib
import phonenumbers
from flask_wtf import Form
from wtforms.fields.html5 import DateField
from app.home.RegisterForm import RegisterForm
from bs4 import BeautifulSoup
import re
from dateutil.relativedelta import *
from datetime import date, datetime
import requests




APP_ROOT = os.path.dirname(os.path.abspath(__file__))



def calculate_age(born_date):
    today = date.today()
    split_date = born_date.split('/')
    dob = date(int(split_date[2]), int(split_date[1]), int(split_date[0]))
    age = relativedelta(today, dob)
    return age.years


def parser():
    try:
        url="https://news.google.com/covid19/map?hl=en-IN&mid=/m/03rk0&gl=IN&ceid=IN:en"
        r = requests.get(url)
        soup = BeautifulSoup(r.content)
    except:
        url = "/data/interview/dezzex/flask-registration-master/app/home/corona_data.html"
        page = open(url)
        soup = BeautifulSoup(page.read())

    
    cities = soup.find_all('tr', {'class' : 'sgXwHf wdLSAe YvL7re'})
    try:    
        table_html = str(soup.find_all('table', {'class':'pH8O4c'})[0]).replace('class="pH8O4c"', 'class="pH8O4c" style="width:100%"').replace('Sorted by Confirmed in descending order','')
    except:
        table_html = None
    return table_html

def PasswordCreate(user_in):
    password1 = hashlib.md5()
    password1.update(user_in.encode("utf-8"))
    return password1.hexdigest()


@login_manager.user_loader
def load_user(email):
    users = mongo.db.users.find_one({'email': email})
    if not users:
        return None
    return User(users['email'])


@home.route('/')
def start():
    return render_template('index.html')



@home.route('/sign', methods=['POST', 'GET'])
def sign():
    if request.method == 'POST':
        email = request.form['inputEmail']
        user_name = request.form['inputUserName']
        password = request.form['inputPassword']
        corona_table = parser()
        

        user = mongo.db.users.find_one({'email': email})
        if user:
            if User.validate_login(user['password'], password):
                image_location = mongo.db.users.find_one({'email': email})['image'].split('/')[-1]
                session['user-email']=email
                session['user-name']=user_name
                session['table-data']=corona_table
                session['user-image']=image_location
                user_obj = User(email)
                login_user(user_obj)
                return redirect(url_for('user.profile'))
            else:
                print('Incorrect Credentials')
        else:
            return redirect(url_for('home.register'))
    return render_template('home/sign.html')



@home.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        password_md5 = PasswordCreate(password)
        inputFullName = request.form['full_name']
        inputDOB = request.form['dob']
        inputPassport = request.form['passport']
        inputPhone = request.form['phone_number']
        inputUserName = request.form['username']
        ageField = calculate_age(inputDOB)


        target = os.path.join(APP_ROOT, 'user-images')  #folder path
        if not os.path.isdir(target):
                os.mkdir(target)     # create folder if not exits

        filename = secure_filename(form.image_file.data.filename)
        destination = "/".join([target, filename])
        form.image_file.data.save(destination)


        if mongo.db.users.find_one({'email': email}):
            return redirect(url_for('home.sign'))
        else:
            mongo.db.users.insert({'email': email, 'password': password_md5, 'age':ageField, 'full_name':inputFullName, 'DOB':inputDOB, 'passport_number':inputPassport, 'phone_number':inputPhone, 'user_name':inputUserName, 'image':destination})
            return redirect(url_for('home.sign'))

    return render_template('home/register.html', form = form)

app/master/__init__.py
from flask import Blueprint

master = Blueprint('master', __name__)

app/user/__init__.py
from flask import Blueprint

user = Blueprint('user', __name__)

from app.user import routes

app/user/routes.py
from flask import render_template, redirect, url_for, session
from flask_login import logout_user, login_required
from app.user import user
from flask import Markup



@user.route('/profile')
@login_required
def profile():
	return render_template('user/profile.html', email=session['user-email'], user_name=session['user-name'], table_data=Markup(session['table-data']), user_image=session['user-image'])


@user.route('/logout')
@login_required
def logout():
    logout_user()
    session.pop('user-email') #deteting the variable at end of session
    return redirect(url_for('home.start'))

app/templates/home/register.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Dezzex</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='assets/css/bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='assets/css/bootstrap-theme.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='assets/css/main.css') }}">

</head>


{% block css %}
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='assets/css/signin.css')}}" />

{% endblock %}

{% block content %}
<div class="container">
        
{% for message in form.full_name.errors %}
 <div>{{ message }}</div>
{% endfor %}

{% for message in form.email.errors %}
 <div>{{ message }}</div>
{% endfor %}

{% for message in form.phone_number.errors %}
 <div>{{ message }}</div>
{% endfor %}

{% for message in form.passport.errors %}
 <div>{{ message }}</div>
{% endfor %}

{% for message in form.dob.errors %}
 <div>{{ message }}</div>
{% endfor %}

<form class="form-signin" action = "http://localhost:5000/register" method = post enctype="multipart/form-data">
 <fieldset>
    <h2 class="form-signin-heading">Register</h2>
    {{ form.hidden_tag() }}
    
    <div class="form-control">
       {{ form.full_name.label }}<br>
       {{ form.full_name(class_="form-control") }}
       <br>

       

       {{ form.dob.label }}<br>
       {{ form.dob(class_="form-control") }}

       <br>

       {{ form.email.label }}<br>
       {{ form.email(class_="form-control") }}
       <br>
       
       {{ form.phone_number.label }}<br>
       {{ form.phone_number(class_="form-control") }}
       <br>
       
       {{ form.passport.label }}<br>
       {{ form.passport(class_="form-control") }}
       <br>

       {{ form.username.label }}<br>
       {{ form.username(class_="form-control") }}
       <br>

       {{ form.password.label }}<br>
       {{ form.password(class_="form-control") }}
       <br>

       {{ form.hidden_tag() }}
       {{ form.image_file.label }}<br>
    {{ form.image_file(class_="form-control") }}
       <br>
       {{ form.submit(class="btn btn-lg btn-primary btn-block") }}
    </div>
    
 </fieldset>
</form>

</div>
{% endblock %}
</html>

app/templates/home/sign.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Dezzex</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='assets/css/bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='assets/css/bootstrap-theme.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='assets/css/main.css') }}">

</head>

{% block css %}
     <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='assets/css/signin.css')}}" />
{% endblock %}

{% block content %}
    <div class="container">

      <form class="form-signin" method="post">
        <h2 class="form-signin-heading">SignIn</h2>
        <input type="email" id="inputEmail" name="inputEmail" class="form-control" placeholder="Email address" required autofocus>
        <input type="username" id="inputUserName" name="inputUserName" class="form-control" placeholder="User Name" required>
        <input type="password" id="inputPassword" class="form-control" name="inputPassword" placeholder="Password" required><br>
        <button class="btn btn-lg btn-primary btn-block" type="submit">SignIn</button>
      </form>

    </div>


{% endblock %}

</html>

app/templates/index.html
<html>
    <head>
        <!--link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css"-->
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="static/css/main.css">
        {% if css %}
            {{css|safe}}
        {% endif %}
        <title>Dezzex</title>
    </head>

    <style>
        h1 {
    width:500px;
    margin: 0 auto;
    background: pink;
    text-align: center;
}
.wrapper{
text-align: center;  
font-size: 30px;  
}
    </style>
    <body>
        <div class='wrapper' class='container-fluid'>
        {% if header %}
            <div id='header' class='col-md-offset-1 col-md-10'>
                <div class='col-md-4 col-lg-3 col-xl-2'>
                    {% if 'image' in header %}
                        <img class='{{header.image.class}}' src='{{header.image.src}}' alt='{{header.image.alt}}'></img>
                    {% endif %}
                </div>
                <div class='col-md-8 col-lg-9 col-xl-10'>
                    <div class='col-md-12 socialButtons'>
                        <div class="g-plusone" data-width="120" data-href="http://www.bnjmnjhnsn.com/"></div>
                        <div class="fb-share-button" data-href="http://www.bnjmnjhnsn.com/" data-layout="button_count"></div>
                        <div><script type="IN/Share" data-url="http://www.bnjmnjhnsn.com" data-counter="right"></script></div>
                    </div>
                    <div class='col-md-12 col-lg-7'>
                        <h2 class='subheader'>{{header.line}}</h2>
                    </div>
                    <div class='col-xs-0 col-sm-0 col-md-0 col-lg-5 height-30'>&nbsp;</div>
                    <div class='col-md-12 col-lg-5'>
                    </div>
                </div>
            </div>
        {% endif %}
        <h1>Dezzex - Flask Web Application</h1>
        <div id='content' class='col-md-offset-1 col-md-10'>
                {% block content %}{% endblock %}
                <div class='col-md-12 footerSpace'>&nbsp;</div>
            </div>
                <hr/>
                <div class='nav col-md-12'>
                    <ul>
                        <li>
                            <a href='{{request.url_root}}' title='Home' {% if 'index' in request.path or request.path=='/' %}class='selected'{% endif %}>
                                Home
                            </a>
                        </li>
                        <li>&mdash;</li>
                        <li>
                            <a href='register' title='Register' {% if 'register' in request.path %}class='selected'{% endif %}>
                                Register
                            </a>
                        </li>
                        <li>&mdash;</li>
                        <li>
                            <a href='sign' title='SignIn' {% if 'sign' in request.path %}class='selected'{% endif %}>
                                SignIn
                            </a>
                        </li>
                        
                    </ul>
                </div>
                
        </div>
        <div id="fb-root"></div>
        
    </body>
    {% if js %}
        {{js|safe}}
    {% endif %}
    <script src="//platform.linkedin.com/in.js" type="text/javascript"> lang: en_US</script>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    <script type="text/javascript">
  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/platform.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>
</html>

app/templates/user/profile.html
{% block css %}


<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='assets/css/profile.css')}}" />
{% endblock %}

{% block content %}
<p><b>Welcome {{ user_name  }} !</b></p>
   <img src="{{ url_for('static', filename=user_image) }}">
<div class="inter">
	
    <a href="{{ url_for('user.logout') }}">Logout</a>
</div>

<h4><b><< Scrapped Corona Data >></b></h4>


{{  table_data  }}
{% endblock %}